spring.application.name=products

# Configuration H2 Database
spring.datasource.url=jdbc:h2:mem:productsdb
spring.datasource.username=sa
spring.datasource.password=

# Habiliting console H2
# URL to access the H2 console 'http://localhost:8080/h2-console'
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuration JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true